version: 0.2

phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - docker build -t pedrops-ecr .
      - docker tag pedrops-ecr:latest 086256341561.dkr.ecr.us-east-1.amazonaws.com/pedrops-ecr:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 086256341561.dkr.ecr.us-east-1.amazonaws.com/pedrops-ecr:latest
